version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      - cypress/run:
          install-browsers: true
          cypress-command: 'npx cypress run --browser chrome'
          cypress-command: 'npx mochawesome-merge cypress/report/mochawesome-report/*.json > cypress/report/combine-report/$(date +"%m-%d-%Y")_final-result.json'
          cypress-command: 'npx marge cypress/report/combine-report/$(date +"%m-%d-%Y")_final-result.json -o cypress/report/final-report --inline'
          

